# Generated by Django 3.1.7 on 2021-02-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type0', models.TextField()),
                ('type1', models.TextField()),
                ('type2', models.TextField()),
            ],
        ),
    ]
