# Generated by Django 3.1.7 on 2021-02-26 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_add', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='type1',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='type2',
        ),
    ]
