# Generated by Django 3.1.7 on 2021-02-26 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_add', '0002_auto_20210226_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='type0',
        ),
        migrations.AddField(
            model_name='pizza',
            name='Pizza_type',
            field=models.CharField(choices=[('regular', 'regular'), ('square', 'square')], default='regular', max_length=18),
        ),
        migrations.AddField(
            model_name='pizza',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
    ]
